### ISSUE TITLE
Add option for direct velocity -> volume conversion

### ISSUE THREAD

**Issue by caryoscelus** [openAVproductions/openAV-Fabla2#45]
It looks like right now note velocity is only used to determine which sample to play. It would be nice to have alternative of velocity directly changing volume or, even better, option to combine both methods.

**Comment by harryhaaren** [comment]
Yes you're right - an option to add a velocity to volume mapping makes sense, but velocity to *both* volume *and* which sample makes no sense to me. The samples will be organized by "intensity" by the user, and if we modify the volume, it will only cause thier work to be un-done?

**Comment by caryoscelus** [comment]
The idea is to have several samples and interpolate in-between volumes to have smooth volume curve. This can be tricky to tune properly, depending on sample volumes. Alternative solution could be to mix two nearest layers in different proportions depending on velocity. Also would be nice to be able to fine-tune these stuff (e.g. choose which layer activates at which velocity).

**Comment by harryhaaren** [comment]
Ah, sorry I misunderstood your first "fade volume" idea then - you mean to trigger two voices, both with different volume settings based on the velocity? That could be interesting yes, although with > 3 velocity layers, I don't the effect on the overall will be huge.

Re: choosing specific samples for specific velocity ranges, this can already be achieved now, using the UI "Velocity Map" dials :)

**Comment by caryoscelus** [comment]
Hmm, there are so much possible various flavours of interpolation, actually.

1. My initial idea: for each velocity range, use one sample and change its volume (needs a lot of tuning so that sample-changing points would be seamless).

2. Each sample has a single velocity point at which it is played at 100% volume. For every other velocity, left and right sample are mixed with volumes according to their proximity.

3. Each layer has a velocity-to-volume map (preferably using curves, but could be simplified using dials) and all layers with non-zero volume are mixed. This allows for maximum flexibility, including simulation of first two options (though requires more tuning than option 2 if such behaviour is desired).

Note that i may not quite understand how current layering is supposed to work as it doesn't seem to work at all for me (just discovered this).

**Comment by harryhaaren** [comment]
The "Switch Mode" dial has to be set to 2 or 3, for round robin or velocity map functionality. I know this stuff needs proper tutorials / documentation when it is released.

**Comment by caryoscelus** [comment]
Ah, i see. Thx for explaining.

Anyway, i might look into implementing some of this, at least that one-sample mode.

**Comment by harryhaaren** [comment]
Sure, one-sample mode is important. I think there are other items probably more interesting to work on instead of the "interpolate between multiple samples"... per Voice FX come to mind! Filtering, distortion, etc can all be done *per voice* (not per sample, but dynamic during the voice lifetime) that makes for awesome flexibility. If you want juicy ideas :)

**Comment by caryoscelus** [comment]
Well, for now i'm mostly interested in implementing stuff i would immediately use :)

**Comment by harryhaaren** [comment]
Closing since pull-request #49 has been merged.
