### ISSUE TITLE
Record always replaces the first pad's sample, not the selected one

### ISSUE THREAD

**Issue by unfa** [openAVproductions/openAV-Fabla2#56]
I'm very exicited to see such a feature in Fabla 2 anyway - recording samples live will allow for some amazing stuff to be created live, but also will allow fro a very quick, fluid workflow, especially inside a DAW like Ardour, where the recording can take place from anything (live mic, or a master aux out).

A problem I've found is that whenever I hit record - it will replace the first pads's sample, so I cannot record more than one sound with it. I'd love to capture an entire kit, but that seem impossible right now.

**Comment by harryhaaren** [comment]
Ah yes - you're looking to record multiple samples to the same pad? Indeed not possible right now, but would be cool to do. Noted, and marked with the enhancement label. Thanks for the idea/request!

**Comment by unfa** [comment]
Actually no - I tried recording to different pads, but the capture always replaced sound on the pad 1. I'll see if that happens still though with a new version.

**Comment by unfa** [comment]
I tested a fresh build and this issue seems to no longer exist. Closing.
