### ISSUE TITLE
Ignoring Note-Off?

### ISSUE THREAD

**Issue by unfa** [openAVproductions/openAV-Fabla2#65]
Hydrogen drum machine has an option to ignore MIDI note-offs.
I always had that on, because otherwise the notes will end sooner if I release the pad. And to play fast I need to release the pads quickly, and the samples get very short and stuttery.

I tried working this out with ADSR (Release) but I'm not sure about the results.

AFAIK having Note-off ignored and having a special envelope that'll ignore note offs doesn't always yield the same results.

What do you think?

**Comment by harryhaaren** [comment]
This functionality is already implemented, see the "Trigger Mode" number box (its labelled "TRG" in the middle of the UI). The default is "stop on note off", the other mode allows "ringing out" of the whole sample (aka, stop playing on sample end). Cheers
