### ISSUE TITLE
setting sample to always play until end

### ISSUE THREAD

**Issue by lukeoftheaura** [openAVproductions/openAV-Fabla2#67]
would it be possible to set a sample in fabla2 to always play until the end of the sample, even if the pad is no longer pressed?

**Comment by harryhaaren** [comment]
Hey Luke, yes this functionality is already implemented (and tested here - works fine : ) see this for details!

https://github.com/openAVproductions/openAV-Fabla2/issues/65

Cheers, -Harry

**Comment by lukeoftheaura** [comment]
ah, thanks! I didn't see that option available.

**Comment by harryhaaren** [comment]
Agreed that documentation is quite lacking for F2.. So much to do! Thanks for closing -H
