### ISSUE TITLE
Amplitude Envelope is not recalled

### ISSUE THREAD

**Issue by unfa** [openAVproductions/openAV-Fabla2#72]
Fabla 2 seems to set all the ADSR parameters to 0 at loading the session.
Not sure if they re not stored in the first place, or not restored afterwards.

**Comment by harryhaaren** [comment]
Known issue - the ADSR is incomplete, buggy and not hardened code. Thanks for reporting.

**Comment by harryhaaren** [comment]
Removed "Ardour" from title to ensure no confusion - this is a Fabla2 issue, and not due to Ardour.

**Comment by unfa** [comment]
Thanks. This one bug makes Fabla2 pretty unusable for me. If this was fixed I could deploy it more and report more bugs.

**Comment by harryhaaren** [comment]
Hey @unfa - thanks for the ping on this. Correct - ADSR restore seems to have a bug on restore (as well as other known ADSR issues). Fixing now...

**Comment by harryhaaren** [comment]
Thanks @unfa for the ping, fixed & merged this quick, given its a trivial fix.
