### ISSUE TITLE
Weird font problem: symbols instead of characters

### ISSUE THREAD

**Issue by afduarte** [openAVproductions/openAV-Fabla2#74]
Hi,
I have been using Fabla for a while, so when I found out about Fabla 2.0, I wanted to test it immediately.

I'm running Manjaro Linux (Based on Arch)
GNOME
VST Host: Usually Ardour but I see the problem in others like Carla as well.
The problem is the following:

![image](https://user-images.githubusercontent.com/9434822/33219664-814d3772-d13b-11e7-91ed-eb7931693ac2.png)

As you can see, the fonts are not rendering properly.
I read on #27 that Fabla uses the system font and I didn't have time to test changing the system font yet, but I will try that and update this issue.

In the meantime, if there is anything I can sot here that might help figure out what the issue is, just let me know.

**Comment by harryhaaren** [comment]
Hi!
Yes that looks like a font issue; You'll see that AVTK selects a font family called "impact", which usually is a bolder or easier to see font (its not always the same - depends on what your system has installed as an "impact" font)....

Eg: https://github.com/openAVproductions/openAV-Fabla2/blob/master/src/ui/avtk/avtk/listitem.cxx#L61

In short, there's no easy way to fix this without embedding a font in the UI. This is probably the only solution for a x-platform font, if we want to gaurantee what it looks like. As a fix that can be done now, installing an "impact" font will fix this I'd imagine.

Thanks for noting this issue, and double thanks for doing the research on it for me :) Cheers, -Harry

**Comment by afduarte** [comment]
Hi, thanks for the quick reply!
![image](https://user-images.githubusercontent.com/9434822/33276445-81895438-d38d-11e7-8010-d0188f95f192.png)
As you can see, that fixed it. 
For anyone visiting this page using Arch, i installed [ttf-ms-corefonts](https://aur.archlinux.org/packages/ttf-ms-fonts/) from the AUR.

**Comment by harryhaaren** [comment]
@afduarte, thanks for the update for future readers and closing!
