### ISSUE TITLE
Strange charset

### ISSUE THREAD

**Issue by m0n0l0c0** [openAVproductions/openAV-Fabla2#77]
Hello all,

First of all, thank you very much for the great effort put on this open source project!! :).

I am trying to get fabla2 to work, but the charset renders really weird. No error was thrown in compile time. Am I missing something?

I launch the plugin in standalone mode with `jalv.gtk3 http://www.openavproductions.com/fabla2`, please find attached the rendered view.

![fabla](https://user-images.githubusercontent.com/6652222/40834805-1ad9ab60-6592-11e8-8cb8-36d7977d6550.png)

Thanks in advance!
Guillermo.

**Comment by georgkrause** [comment]
#74 ;)

Which OS are you using?

**Comment by m0n0l0c0** [comment]
Hi @georgkrause,

I'm using Arch based Antergos OS.

**Comment by georgkrause** [comment]
In this case the solution is in the link above

**Comment by m0n0l0c0** [comment]
@georgkrause thak you!

It worked, sorry for the inconvenience, didn't even see it :(

Best,
Guillermo.

**Comment by harryhaaren** [comment]
Nice one @georgkrause, glad its working now @m0n0l0c0! Let me know how you get on with F2, there are some known issues, the basic features are stable here.

Cheers, -Harry

**Comment by georgkrause** [comment]
@harryhaaren might be a good idea to add a hint to the readme...
