### ISSUE TITLE
Recording audio for samples.

### ISSUE THREAD

**Issue by Qualphey** [openAVproductions/openAV-Fabla2#78]
Is there any way to record samples using a microphone instead of loading them from the file system?

**Comment by harryhaaren** [comment]
Hi @Qualphey! Yes there is, it uses ControlPort index 16 labelled `record_over_last_played_pad`. Its a "int" and "toggled" port, meaning its essentially just a binary switch. Press and hold the record_over_last_pad, and F2 will record the audio data into the pad.

This enables workflows where you press a pad, press and hold `record over last pad` high while making a sound (guitar/mic etc whatever) and that audio is now present in the pad. Release the momentary `record over last pad` to stop sampling.

Press next pad, hold `record over`, release, and repeat for each pad you want to record to :) Hope that helps!

**Comment by Qualphey** [comment]
Whichever pad I select, when I click the `REC` button and then click again to stop recording, the sample does get recorded, but always on the most bottom-left pad? Am I missing something?
