### ISSUE TITLE
Playing a pad without interrupting another.

### ISSUE THREAD

**Issue by Qualphey** [openAVproductions/openAV-Fabla2#80]
As far as I've tested this plugin, there is no way to play samples from more than one pad at the same time. Would it be hard to implement this feature?

**Comment by harryhaaren** [comment]
I'm not sure how you're testing that it isn't playing multiple samples at the same time... yes Fabla2 is capable of having multiple samples playing at the same time, (fabla1 can and does this too).

The sample playback in F2 is actually quite sophisticated, in that it supports playback of a single sample multiple times, multiple samples at the same time, multiple samples all playing multiple times, and even a "Layers" feature that allows one pad to have multiple *different* samples that then play at the same time.

So somethings strange in how this is being tested - perhaps put a MIDI monitor plugin before F2, or printf() the midi messages to debug, i expect there are MIDI note off messages turning off the notes.

**Comment by Qualphey** [comment]
Well actually I don't even have any physical MIDI devices like a drum pad or some kind of sampler, cah I can't afford it at the moment. So I'm simply using the
```
1 2 3 4
q w e r
a s d f
z x c v
```
keyboard shortcuts or using my mouse. Also the samples play only as long as you hold the keyboard key and it stops when you release (the key). I think it should have something more like on/off behavior with an option to loop the sample.
The pads don't light up when you're using keyboard shortcuts. It's also kinda glitchy with the mouse.
Could you please point me to some source files, related to keyboard/mouse input and pad GUI? If I would succeed making some fixes then we could definitely merge my fork with this project.
^^

**Comment by harryhaaren** [comment]
Hi Qualphey, as you can see I'm not active much on here recently... I don't think that the keyboard support you're looking for is going to be implemented (soon) so will close this.

Fabla2 really is made for MIDI/USB hardware controls... perhaps driving F2 with a SW MIDI sequencer such as Ardour, QTractor or otherwise might be interesting?
